### ISSUE TITLE
Mission Tree for New Tag Pontus

### ISSUE THREAD

**Issue by Brother-Zael** [PitiRR/pitirr-eu4-rp-mod#1]
Resurgent Pontic empire missions focused on reclaiming former pontic kingdom lands, securing borders with slight expansion from there, and becoming a regional power. Pontus was known for great multiculturalism, black sea trade, and adopting effective military tools as they were introduced. Trebizond (or chosen capital) should get good dev. Not "tall" nation per se, but definitely not a blobber.

**Comment by PitiRR** [comment]
Resolved with release [v0.1.0 "Pontus"](https://github.com/PitiRR/pitirr-eu4-rp-mod/releases/tag/v0.1.0).

**Comment by Envy23** [comment]
I was thinking of somehow introducing Janissaries or some form of special units if the said nation is of a different religion say Islam and maybe ( idk if that's allowed) to make a special gov't for them for ex: "the Pontic Empire" giving off idk cultural conversion cost, it'd be fun to play around with the choosing an heir after the emperor's death albeit it's not necessary 
give that absolutism and idk what kind of modifier to make it interesting idk what kind of modifiers can be given to them to be fair.
