### ISSUE TITLE
[IDEA] Replace Slacken Modifiers

### ISSUE THREAD

**Issue by Brother-Zael** [PitiRR/pitirr-eu4-rp-mod#13]
Replace the Slacken Recruitment Standards modifiers from a lump-sum of manpower to a 5 year bonus giving +50% mp/sailors recovery, -10% regiment cost modifier, +10% reinforce speed, and -10% recruitment speed. If 5 years or the mods seem wonky, change to whatever you think is best (we can always modify it later).

**Comment by PitiRR** [comment]
I don't think it's possible. 

Slacken recruitment standards is defined only in `defines.lua`, line 1221 and 1222.
```
	SLACKEN_AP_DROP = 0.05,
	SLACKEN_MANPOWER_INCREASE = 1.0,
```
[On_Actions](https://eu4.paradoxwikis.com/On_Actions) doesn't seem to light up anything relevant.

I'm not sure if 5 years worth of manpower is too much. I think 2.5 could be a good, simple buff. How would this change interact with the ideagroups mod?

**Comment by PitiRR** [comment]
Closing as it's not really necessary and decent as it's now with vanilla - it's nice to not have infinite manpower.
