### ISSUE TITLE
Updated National Ideas and MT for Pomerania

### ISSUE THREAD

**Issue by Brother-Zael** [PitiRR/pitirr-eu4-rp-mod#3]
National Ideas 
[Already Done]
Put some good mil buffs in missions that take a while to get. I want this to be rewarding but also encourage the player to not form prussia.

Mission Tree (Tbh I don't know much about Pomerania, esp. during this time. I just want something viable where he doesn't feel forced to form prussia and curb stomp everyone).
- Move "Unite Pomerania" to slot 2
- Leave rest of slots 1 and 2 as-is
- Slot 3 after (and requiring) "unite pomerania" missions to build up capital, invest in trade centers, develop hinterland, and construct universities.
- After these 3 lines, add mission on claiming estonia and novgorod, which then gives claim on rest of baltic sea bordering provinces.
- Slot 4, build up military missions. first 2 are for army, next 2 are for navy, last one (be on par with rivals) is for both with perma buff.

**Comment by PitiRR** [comment]
![image](https://user-images.githubusercontent.com/48140510/202513226-3656dc4b-d2e3-40fb-94f5-21a633e56e23.png)

I decided to go a little off-board from the requirements here and did this (the last mission not viewable gives permaclaims on all Baltic ports). The army and navy missions check for discipline, ICA, galley power and Naval Forcelimit modifiers
