### ISSUE TITLE
New MT for New Tag Slovenia

### ISSUE THREAD

**Issue by Brother-Zael** [PitiRR/pitirr-eu4-rp-mod#4]
Mega-tall tag. Slovenia during this time was kinda bussin. They became protestant and had huge innovations, but then got hammered hard by the coutner reformation and went full catholic - so maybe some missions "if protestant get this, if catholic get this". Militarily they should focus on supreme defense in homeland, as they were often used as a battlefield between the hapsburgs and the ottomans. They also got mega-developed during this time, and had architecture, artists, scientists, and thinkers galore settle in and develop the region. Missions should enable extremely tall play but ONLY in slovenia and maybe nearby croatia and bosnia. Should allow huge dev-cost reduction, defensiveness, and maybe even dice roll for defenders, but only in culture areas and only for this tag (if others take their land, they don't get the bonus).

**Comment by PitiRR** [comment]
Note to future self - dice roll for defenders is possible and seamless to introduce with `local_defender_dice_roll_bonus` (or `own_territory_dice_roll_bonus `). Just add it to a local modifier.
