### ISSUE TITLE
[IDEA] Missions for New Tag Sarmatia

### ISSUE THREAD

**Issue by Brother-Zael** [PitiRR/pitirr-eu4-rp-mod#5]
Focus on regional blobbing, cavalry, and overland asian/black sea trade. Uses Sich Rada government. Missions should see them invading carpathian basis, ruthenia, and ESPECIALLY linking up with the Alans, who are the last remaining Scythians/Sarmatians. Religious missions should be geared towards religious tolerance (perhaps add some dhimmi-like privileges?) promoting cultures, and accepted cultural manpower, as the Sarmatians were known to incorporate others into their realm. They should have a mission doing diplomacy with the pontic empire (or if doesn't exist, owner of trebizond) regarding the fate of the crimean peninsula - trading it for permabuffs or something. End game should be geared towards entering into central europe/italy, with possible expansion into greece, heartland russia, and towards asia once the homeland is secure. Institution spread would be nice to see alongside provincial trade power.

**Comment by PitiRR** [comment]
Abandoning Sarmatia, as it was pure fiction, made purely for one-time fanserice. Closing.
