### ISSUE TITLE
[IDEA] Update Mission Tree for Mamluks.

### ISSUE THREAD

**Issue by Brother-Zael** [PitiRR/pitirr-eu4-rp-mod#8]
Mission tree focusing on conquering aden, allying muslim nation in the horn (ajuraan or adal preferred). Later on you can try to restoration of union cb (i think this can be done even for muslims, i believe multan has it by event) or let them be giving a bunch of mana and (yearly?) money. Add missions to build up Med fleet (Fleet to FL) then get to invade crete then byz, giving morea OR Halab 20 year mega defensiveness. Add missions about vassal swarming arabia and north africa (50 year modifier give dip relations and making it easier to integrate?), then invading italy. Missions to rival ottomans and kill them that progress mutually with taking crete and byz lands (focus is on using superior navy/position to distract ottomans in morea or halab wile you push elswhere). Once owning thrace, ally poland/sarmatia/whoever and let them have bulgaria/carpathia in return for progressively better buffs (yearly income "tithes", mp recovery "immigrants", and cca "hussar guard"). Then missions focus on working your way up through ragusa and italy to dominate venice node. After vassal swarm arabia, missions to control basra and hormuz, build up pacfic fleet, and get baluchistan. Then either own gujurat or ally indian person. If latter, you get bonus ship trade power and hormuz gets mega buff (letting you steal indian trade anyway), but declaring on an indian tag gives you stab hits. After baluchistan mission, get claims on persian states you border/contest. Mission to "finish the job" and take kurdistan/iraq should be added as well.

Mamluks should get bonus to slave trade if possible. Mamluks should have access to professional merc companies that are more useful early on. After they take constantinople, or Ottomans no longer exist, they can pop mission to get access to jannisaries, but this removes access to early game merc companies. Army/navy should focus on guerrilla warfare, fast movement, and attrition, along with decent cav and later good drill.

**Comment by Brother-Zael** [comment]
![mamluk_MT](https://user-images.githubusercontent.com/59200644/202124065-48a866a7-1bf9-4bee-b5f1-61e15b1ec6e7.PNG)

**Comment by PitiRR** [comment]
Updated with KoK
