### ISSUE TITLE
[IDEA] Update MTs and NIs for Arabia

### ISSUE THREAD

**Issue by Brother-Zael** [PitiRR/pitirr-eu4-rp-mod#9]
Give option to go feudal theocracy or Tribal Federation (maybe use Mossi Tribal Confederation). Focus on developing trade provinces, building up a formidable navy, and protecting the borders. Gain bonus to fighting in desert and mountains. Mission to unite the tribes and get access to banners (larp is arabic tribal culture tradition). Choose capital out of cairo, demascus, baghdad, basra, medina, sana'a, or hormuz. Get access to desert dev cost estate privilege (i think ajuraan has it?). Max absolutism and estate loyalty (to larp as increasing control of the tribes like how the saudis came to power). Ultimately idea is that you've already reached peak blob by the time you formed arabia so missions should focus on buffing the land you got, your grip over spice trade, and innovative manuever warfare (horse tradition + tuskan raider memes).

**Comment by PitiRR** [comment]
Updated with KoK
